--- !ditz.rubyforge.org,2008-03-06/project 
name: haitus
version: "0.3"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: haitus
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.1"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2008-06-14 11:52:41.878760 Z
    - Austin Seipp <mad.one@gmail.com>
    - created
    - ""
